[package]
name = "decibel_vault"
version = "1.0.0"
authors = []

[addresses]
decibel_dex = "_"
orderbook_dep = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
# follow fixed order book from aptos-core version that we depend on,
# and update together with appropriate changes to new version.
rev = "c31852e888970ccc6597983dbcba33bc9f186fcd"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
decibel_perp_dex = { local = "../perp" }
decibel_accounts = { local = "../accounts" }
